apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: xabn1eyq2-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xabn1eyq2-go 
  name: xabn1eyq2-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: xabn1eyq2-go 
